
info:
    app:
        name: Annotation Image Application
        description: StatNLP Service Annotation Image Application
        version: 1.0.0

logging:
    level:
        ROOT: DEBUG
        com.sutd.statnlp: DEBUG

management:
    security:
        enabled: false

spring:
    application:
        name:  Annotation Image App
    devtools:
        restart:
            enabled: true
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: AnnotationImage

server:
    port: 8082


springfox:
    documentation:
        swagger:
              v2:
                  path: /api-docs

application:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    mail:
        from: AnnotationImage@localhost
    swagger:
        default-include-pattern: /api/*
        title: AnnotationImage API
        description: AnnotationImage API documentation
        version: 0.0.1